---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-extended-clusterrole
rules:
  - apiGroups:
    - "*"
    resources:
      - "*"
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-extended-clusterrolebinding
roleRef:
  kind: ClusterRole
  name: argocd-extended-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: coffeeshop-argocd-argocd-application-controller
  namespace: coffeeshop-gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: coffeeshop-gitops
roleRef:
  kind: ClusterRole
  name: argocd-extended-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: coffeeshop-argocd-argocd-application-controller
  namespace: coffeeshop-gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: coffeeshop-pipeline
roleRef:
  kind: ClusterRole
  name: argocd-extended-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: coffeeshop-argocd-argocd-application-controller
  namespace: coffeeshop-gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: coffeeshop-dev
roleRef:
  kind: ClusterRole
  name: argocd-extended-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: coffeeshop-argocd-argocd-application-controller
  namespace: coffeeshop-gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: coffeeshop-prod
roleRef:
  kind: ClusterRole
  name: argocd-extended-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: coffeeshop-argocd-argocd-application-controller
  namespace: coffeeshop-gitops
...