---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-extended-clusterrole
rules:
  - apiGroups:
    - "*"
    resources:
      - "*"
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-extended-clusterrolebinding
roleRef:
  kind: ClusterRole
  name: argocd-extended-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: coffeeshop-argocd-argocd-application-controller
  namespace: coffeeshop-gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-admin-coffeeshop-gitops
  namespace: coffeeshop-gitops
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: coffeeshop-argocd-argocd-application-controller
  namespace: coffeeshop-gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-admin-coffeeshop-pipeline
  namespace: coffeeshop-pipeline
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: coffeeshop-argocd-argocd-application-controller
  namespace: coffeeshop-gitops
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: argocd-admin-coffeeshop-dev
#   namespace: coffeeshop-dev
# roleRef:
#   kind: ClusterRole
#   name: admin
#   apiGroup: rbac.authorization.k8s.io
# subjects:
# - kind: ServiceAccount
#   name: coffeeshop-argocd-argocd-application-controller
#   namespace: coffeeshop-gitops
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: argocd-admin-coffeeshop-prod
#   namespace: coffeeshop-prod
# roleRef:
#   kind: ClusterRole
#   name: admin
#   apiGroup: rbac.authorization.k8s.io
# subjects:
# - kind: ServiceAccount
#   name: coffeeshop-argocd-argocd-application-controller
#   namespace: coffeeshop-gitops
...