apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffeeshop-dev
spec:
  project: coffeeshop
  source:
    path: coffeeshop/overlays/dev/
    repoURL: https://github.com/froberge/coffeeshop-deploy
    targetRevision: main
  destination:
    namespace: coffeeshop-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true