apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: coffeeshop-gitops

resources:
- coffeeshop-project.yaml
- coffeeshop-dev.yaml
- coffeeshop-prod.yaml
- coffeeshop-pipeline.yaml