apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: gitops-demo-argocd
  namespace: gitops-demo-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  applicationSet: {}
  controller:
    processors: {}
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  ha:
    enabled: false
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    insecure: true
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
