apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffeeshop-dev
  namespace: coffeeshop-dev
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    path: 
    repoURL: 
    targetRevision: main
  destination:
    namespace: coffeeshop-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true