apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffeeshop-pipelines
  namespace: coffeeshop-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    path: tekton
    repoURL: https://github.com/froberge/ocp-pipeline-demo/
    targetRevision: main
  destination:
    namespace: coffeeshop-pipeline
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true