apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-dev
  namespace: gitops-demo-dev
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    path: app/overlays/dev/
    repoURL: https://github.com/RedHatWorkshops/welcome-deploy/
    targetRevision: main
  destination:
    namespace: gitops-demo-dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true