apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-prod
  namespace: gitops-demo-prod
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    path: 
    repoURL:
    targetRevision: main
  destination:
    namespace: gitops-demo-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true