kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: gitops-demo
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: gitops-demo
  source:
    path: cluster-apps/tekton
    repoURL: https://github.com/froberge/ocp-gitops-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true